# This workflow validate commit messages.
# It is supposed to be run only when:
#   - the push is done to the main;
#   OR
#   - pull request is open to the main;

name: Conventional commit

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
