# This workflow validate commit messages.
# It is supposed to be run only when:
#   - the push is done to the main;
#   OR
#   - pull request is open to the main;

name: Conventional commit

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
