# This workflow run linters.
# It is supposed to be run on each push to main branch, as well as for each.

name: Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.53
          skip-cache: true
