# This workflow run tests.
# It is supposed to be run on each push to main branch, as well as for each.

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  tests:
    name: Run tests and upload coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - run: |
          go test -race -covermode=atomic -coverprofile=coverage.out
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
